### ISSUE TITLE
Model object has no attribute 'scan'

### ISSUE THREAD

**Issue by jcouser** [yfilali/graphql-pynamodb#10]
I'm attempting to setup the example and when using a resolver against a model declared from:
pynamodb.models import Model

I'm getting type object 'User' has no attribute 'scan'

Have you seen this before?

**Comment by yfilali** [comment]
No, I haven't seen that before. What version of pynamodb are you using? Models should have scan according to the docs : http://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.models.Model.scan

Maybe I'll spot the issue if you post the User class code.

**Comment by jcouser** [comment]
Ah thanks for the nudge in the right direction.  I was referencing the PynamoObjectType object and not the Model, typo on my part.

One other question, based on the example project how would you filter a User by id? Attempting:

```
{
  user(id: "<uuid>"){
    id
    name
  }
}
```
returns:
Unknown argument "id" on field "employees" of type "Query".
I've done this with sqlalchemy and args.get, but unsure within this framework and dynomodb.

Thanks for the fast response!

**Comment by yfilali** [comment]
Try something like this:

```
query {
  node(id: "RW1wbG95ZWU6NTljY2NmYzYtOTVjMy00YTcwLTllM2YtOTI0MTkzNjJhYzU0") {
    id,
    ... on User {
      name
    }
  }
}
```

Here is more on that: https://facebook.github.io/relay/graphql/objectidentification.htm
