### ISSUE TITLE
NumberAttribute converted to INT

### ISSUE THREAD

**Issue by clement91190** [yfilali/graphql-pynamodb#12]
When converting a table with a NumberAttribute it becomes an INT instead of a Float

https://github.com/yfilali/graphql-pynamodb/blob/master/graphene_pynamodb/converter.py#L57

**Comment by saffrydaffry** [comment]
Agree, that this is a problem for me as well. Not sure how I would solve it, it seems the converter needs to understand the type from the PynamodbObject which is difficult considering you can't control types in Pynamodb Models (I blame DynamoDBs scalars!). Would be nice if, say, you could create a NumberAttribute with the `of=` parameter (like you can with Lists and Maps) and use that value to discern whether a graphene.Int or graphene.Float should be returned.

**Comment by saffrydaffry** [comment]
Would creating an explicit resolver function work?

**Comment by yfilali** [comment]
This should probably default to Float in the converter as it can always be cast to int if need be versus the loss of information from Int.

**Comment by clement91190** [comment]
Yes I agree, I think it should default to Float and eventually have an option for casting to Int directly when writing the schema.
