### ISSUE TITLE
Support for pynamodb 3.0.1

### ISSUE THREAD

**Issue by petecocoon** [yfilali/graphql-pynamodb#14]
Hi guys, when we can expect to use graphql-pynamodb with pynamodb > 3.0.0 (ie. 3.3.1)?

**Comment by yfilali** [comment]
Looks like there were a few breaking changes but nothing major. I'll take a look when I get a chance.

**Comment by yfilali** [comment]
This was pretty straight forward at least according to the tests. The tests are passing but it could use a bit more testing.

**Comment by yfilali** [comment]
Should be good to go, let me know if anyone see any issues
