### ISSUE TITLE
OneToMany issue

### ISSUE THREAD

**Issue by petecocoon** [yfilali/graphql-pynamodb#18]
Hi @yfilali 
I have an issue with OneToMany relation, please check this code:
In my Pynamo model, I have
```
...
    menus = OneToMany('MenuModel', default=list)
...
```
in a mutation i have

```
 ChefModel(
            id=chef_id
        ).update(actions=[
            ChefModel.menus.set(ChefModel.menus.append([menu_item]))
        ])

```

sometimes I get this error:
`'list' object has no attribute 'set'`
on 
`            ChefModel.menus.set(ChefModel.menus.append([menu_item]))
`

do you have an idea?
This happens after I assign to an instance of ChefModel.menu a list in another and totally disjointed part of the code.
```

response = [..some data here.]
chef.menus = response.menus
return chef
```

**Comment by yfilali** [comment]
I haven't tried your example, but the problem is likely that you are appending a list of menu items instead of menus.append(menu_item).

I can take a closer look later tonight.

**Comment by marioscience** [comment]
Sorry to comment on a close issue, not sure if this library is still being actively maintained, but I ran into this exact same issue. Seems that for some reason the list operations (extend, append, etc) are not passed down to OneToMany attributes.

I was trying this:

`update_actions.append(MyModel.nestedattr.set(MyModel.nestedatrr.extend(
                extract_objects_from_id_list(MyModel, args.get("append_nestedattr")) 
            ))`

and found the error  'OneToMany' object has no attribute 'extend'. Maybe the solution would be subclassing from OneToMany but I was wondering if this was intended to be supported in some other way in the original design.
