### ISSUE TITLE
ListAttribute and MapAtrribute Support

### ISSUE THREAD

**Issue by hansbonini** [yfilali/graphql-pynamodb#7]
I got the following exception when a try to use with PynamoDB ListAttribute and MapAttribute:
```sh
Exception: Don't know how to convert the PynamoDB attribute <pynamodb.attributes.ListAttribute object>
```

**Comment by yfilali** [comment]
@hansbonini I'll take a look tonight. It looks like they just need to be added to https://github.com/yfilali/graphql-pynamodb/blob/master/graphene_pynamodb/converter.py

**Comment by hansbonini** [comment]
Thx, this attribute is very important.

**Comment by yfilali** [comment]
@hansbonini Any chance you can give the change a try? I added a few tests, but I need to add more before I publish the package. It would be helpful to have someone else try it especially if you have an existing schema with List and Map attributes.

**Comment by yfilali** [comment]
Pypi package pushed, let me know if you see any issues with the new attributes

**Comment by hansbonini** [comment]
I'll take a look! Thanks

**Comment by daksharma** [comment]
Would you be able to add examples (in the folder) on how to create query on Map/List Attributes.
ex:

```python
class ReceiptItem(MapAttribute):
    name = UnicodeAttribute()
    quantity = NumberAttribute()
    price = NumberAttribute()

class Receipt(Model):
    ...
    id = UnicodeAttribute(hash_key = True)
    items = ListAttribute(null = False, of = ReceiptItem)

class User(Model):
    ...
    name = UnicodeAttribute(null = False)
    receipts = OneToMany(Receipt)

class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_users = PynamoConnectionField(User)
    # ???

schema = graphene.Schema(query = Query, types = [User, Receipt])
```
not sure how to properly get the query for this. In the GraphiQL i get the memory address from the local DynamoDB as a string. I've been learning graphene-pynamodb but kind of got stuck here when trying to create this example.

```
...
receipts {
          edges {
            node {
              items
            }
          }
        }
...
```
in the Graphiql docs it shows up as items: [String]

```json
<model.Receipt.ReceiptItem object at 0x10cb66550>
```
Any help is appreciated. Awesome Python module. :)

**Comment by petecocoon** [comment]
Same issue here, i haven't understand if is an issue of this module or if is a graphene issue, @daksharma did you solve it?
