### ISSUE TITLE
examples are not working

### ISSUE THREAD

**Issue by jameelgrand** [yfilali/graphql-pynamodb#8]
I am getting this error for default query

{
  "errors": [
    {
      "message": "connection_resolver() takes exactly 8 arguments (6 given)",
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ]
    }
  ],

**Comment by yfilali** [comment]
Hi Jameel, could you check if you have graphene and graphql-core 1.x installed? This was not tested with the new 2.x branches of graphene.

**Comment by jameelgrand** [comment]
altgraph==0.10.2
ansible==2.1.0.0
appnope==0.1.0
awscli==1.10.40
backports.shutil-get-terminal-size==1.0.0
bdist-mpkg==0.5.0
bonjour-py==0.3
boto==2.43.0
boto3==1.4.5
botocore==1.5.92
cffi==1.7.0
colorama==0.3.3
cryptography==1.4
decorator==4.0.10
docutils==0.12
enum34==1.1.6
futures==3.0.5
idna==2.1
ipaddress==1.0.16
ipython==5.1.0
ipython-genutils==0.1.0
Jinja2==2.8
jmespath==0.9.0
lxml==3.6.1
macholib==1.5.1
MarkupSafe==0.23
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
paramiko==2.0.1
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.7
ptyprocess==0.5.1
py==1.4.34
py2app==0.7.3
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
Pygments==2.1.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
pytest==3.2.2
pytest-html==1.16.0
pytest-metadata==1.5.0
python-dateutil==2.5.3
pytz==2013.7
PyYAML==3.11
requests==2.11.1
rsa==3.4.2
s3transfer==0.1.10
scipy==0.13.0b1
simplegeneric==0.8.1
six==1.10.0
traitlets==4.2.2
vboxapi==1.0
virtualenv==15.0.2
wcwidth==0.1.7
xattr==0.6.4
zope.interface==4.1.1

**Comment by jameelgrand** [comment]
botocore==1.8.12
click==6.7
docutils==0.14
Flask==0.12
Flask-Cors==3.0.2
Flask-GraphQL==1.4.0
Flask-JWT==0.3.2
graphene==1.2
graphene-pynamodb==0.9.0
graphql-core==2.0
graphql-relay==0.4.5
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
MarkupSafe==1.0
promise==2.1
PyJWT==1.4.2
pynamodb==3.2.1
python-dateutil==2.6.1
Rx==1.6.0
singledispatch==3.4.0.3
six==1.11.0
typing==3.6.2
Werkzeug==0.13
wrapt==1.10.11

**Comment by yfilali** [comment]
Closing now that we are on 2.X graphene/core
