### ISSUE TITLE
Support for graphene >= 2.0?

### ISSUE THREAD

**Issue by samlll42-github** [yfilali/graphql-pynamodb#9]
Looks like only graphene <2.0 is supported. Is there any plan to support 2.x in the near future?

Thanks,

**Comment by yfilali** [comment]
Yes, I planned to work on it as soon as it was finalized. I can't promise a firm timeline, but I might get to it this weekend.

**Comment by yfilali** [comment]
I've done some work on this and it's almost ready. I hit a few snags with connections that I am trying to iron out. I'll push what I've done so far tonight in case anyone can/wants to chime in.

**Comment by omgvamp** [comment]
I am also looking to use this with graphene 2.0+. Any update on when this will be supported?

**Comment by yfilali** [comment]
I rushed a new 2.X branch. The tests are passing but it could use some more testing if either @samlll42-github or @omgvamp can please give it a shot.

I'll push a 2.X release once I've had some time to properly test it.

**Comment by yfilali** [comment]
I pushed the 2.X release to pypi and promoted it to master. The old 1.X is still around in case we need to apply any bug fixes
